import ReduxProvider from '@/provider/ReduxProvider'
import './../globals.css'
import { Roboto, Nunito } from 'next/font/google'
import Footer from './components/shared/Footer'
import Navbar from './components/shared/Navbar'

 
export const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ['latin'],
})
const nunito = Nunito({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ReduxProvider>
          <Navbar/>
          {children}
          <Footer/>
        </ReduxProvider>
      </body>
    </html>
  )
}
