import ReduxProvider from "@/provider/ReduxProvider";
import "./../globals.css";
import { Roboto, Nunito, Inter } from "next/font/google";
import Footer from "./components/shared/Footer";
import Navbar from "./components/shared/Navbar";

export const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});
const nunito = Nunito({
  weight: "400",
  subsets: ["latin"],
});
export const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
<<<<<<< HEAD
  title: 'Glamorex',
  
}
=======
  title: "Create Next App",
  description: "Generated by create next app",
};
>>>>>>> development

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
<<<<<<< HEAD
          <ReduxProvider>
            <Navbar/>
              {children}
            <Footer/>
          </ReduxProvider>
=======
        <ReduxProvider>
          <Navbar />
          {children}
          <Footer />
        </ReduxProvider>
>>>>>>> development
      </body>
    </html>
  );
}
