import ReduxProvider from '@/provider/ReduxProvider'
import './globals.css'
import { Roboto, Nunito } from 'next/font/google'
 
export const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
export const nunito = Nunito({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
